### ISSUE TITLE
ShotGrid python-api v3.4.0

### ISSUE THREAD

**Issue by carlos-villavicencio-adsk** [fabiangeisler/pyshotgrid#28]
* pyshotgrid version: n/a
* Python version: 3.7/3.9/3.10
* Operating System: all

### Description

Hello from the ShotGrid team 👋 ,

I just wanted to let you know that we released [v3.4.0](https://github.com/shotgunsoftware/python-api/releases/tag/v3.4.0) that now supports up to Python 3.10. Feel free to reach out if you have any questions.

**Comment by fabiangeisler** [comment]
Hi @carlos-villavicencio-adsk !
Thanks for the heads up! Will implement it straight away! 
Also hurray for my first issue from someone else! 😄 🎉
