### ISSUE TITLE
New version of ShotGrid Python API v3.4.1

### ISSUE THREAD

**Issue by carlos-villavicencio-adsk** [fabiangeisler/pyshotgrid#41]
* pyshotgrid version:
* Python version:
* Operating System:

### Description

Hello folks, I wanted to share with you a new release of the ShotGrid Python API v3.4.1

### What I Did

- Add methods for the user_subscriptions API endpoints
- Retries also on 504
- Retries S3 uploads on error 500
- Comment typing annotation breaks Python 2 compatibility
- Add field type entity_type to mockgun as simple str
- Full release notes are available on [GitHub](https://github.com/shotgunsoftware/python-api/releases/tag/v3.4.1).

**Comment by fabiangeisler** [comment]
Finally closed with the release of [v2.0.0](https://github.com/fabiangeisler/pyshotgrid/releases/tag/v2.0.0).
